runtime: php
env: flex

runtime_config:
  document_root: .

# [START env_variables]
env_variables:
  SENDGRID_APIKEY: your-sendgrid-api-key
  SENDGRID_SENDER: your-sendgrid-sender
# [END env_variables]
