runtime: php
vm: true

runtime_config:
  document_root: web

# [START env_variables]
env_variables:
  # If you are using the App Engine Memcache service (currently in alpha),
  # uncomment this section and comment out the other Memcache variables.
  # USE_GAE_MEMCACHE: 1
  MEMCACHE_SERVER: your-memcache-server
  # If you are using a Memcached server with SASL authentiation enabled,
  # fill in these values with your username and password.
  MEMCACHE_USERNAME: ""
  MEMCACHE_PASSWORD: ""
# [END env_variables]