runtime: php
env: flex

runtime_config:
  document_root: .

# [START env_variables]
env_variables:
    TWILIO_ACCOUNT_SID: your-account-sid
    TWILIO_AUTH_TOKEN: your-auth-token
    TWILIO_FROM_NUMBER: your-twilio-number
# [END env_variables]
